### ISSUE TITLE
Merging with mos

### ISSUE THREAD

**Issue by zkochan** [Widdershin/markdown-doctest#25]
I've created a package that generates and tests markdown files to keep them up to date. It is called [mos](https://github.com/zkochan/mos)

It has several plugins and the [mos-plugin-example](https://github.com/zkochan/mos/tree/master/plugins/mos-plugin-example) is meant to do the same as markdown-doctest.

Currently it can run js and es6, test the example files and combine the output of the examples with the code that outputs them.

For instance, this example:

```js
console.log('Hello world!')
```

Is transformed into this example in the markdown:

```js
console.log('Hello world!')
//> Hello world!
```

IMHO, we can unite efforts to make these toolings better and more popular.

**Comment by Widdershin** [comment]
Hi @zkochan. Thanks for reaching out.

> It has several plugins and the mos-plugin-example is meant to do the same as markdown-doctest.

I'm not sure if I'm misunderstanding, but it seems like mos-plugin-example modifies the markdown files to insert any values logged to the console. markdown-doctest only runs examples, it doesn't change markdown files.

I'm impressed by all the capabilities that mos has. It definitely solves a bunch of problems I've run into in the past. I'm definitely interested in discussing ways we can collaborate.

Do you have any ideas on how we could unite our efforts?

Also, I tried out mos on [rxjs](https://github.com/ReactiveX/RxJS) v5, which is currently tested by markdown-doctest as part of the CI. It reported that all the files passed, but when I added syntax errors I couldn't get it to pick them up. Does mos test all code examples, or just ones using the mos template syntax?

**Comment by zkochan** [comment]
Hi @Widdershin !

> markdown-doctest only runs examples, it doesn't change markdown files.

Yes, but under the hood, we are solving the same problems, we have to execute the example code. Although currently markdon-doctest might work with a simpler algorithm, because it doesn't need to catch the outputs and insert them to the code.

On the other side of the coin, it is so widespread to inline the output with the examples. IMHO, it is a valuable feature. If you'd decide to support it as well, the core code could be the same, otherwise maybe just parts of it.

There is also this interesting project by @vdemedes - [bucket-app](https://github.com/vdemedes/bucket-app). It tries to solve the same problems and already has an issue for inlining `console.log` output https://github.com/vdemedes/bucket-app/issues/26

> Also, I tried out mos on rxjs v5, which is currently tested by markdown-doctest as part of the CI. It reported that all the files passed, but when I added syntax errors I couldn't get it to pick them up. Does mos test all code examples, or just ones using the mos template syntax?

I think I did not implement handling of all the errors yet. Could you please push your branch and tell me the repo-name/branch so that I can try it?

**Comment by Widdershin** [comment]
> On the other side of the coin, it is so widespread to inline the output with the examples. IMHO, it is a valuable feature. If you'd decide to support it as well, the core code could be the same, otherwise maybe just parts of it.

I agree that it's a useful feature, but it's not my intention to inline output in the future. I'd like to keep markdown-doctest as simple as possible. It's worth noting that RxJS, where markdown-doctest currently runs on CI, would not use inlined output.

It seems like our projects have different aims. mos seems like a much more all encompassing markdown generation solution, whereas markdown-doctest just runs code examples.

> I think I did not implement handling of all the errors yet. Could you please push your branch and tell me the repo-name/branch so that I can try it?

It's here. Running `mos test README.md` doesn't find any errors:

https://github.com/Widdershin/RxJS-1/commit/d00646aadd04aab76ba772561ac7056c17ec0317
