### ISSUE TITLE
Work alongside existing babel 6 installation

### ISSUE THREAD

**Issue by briancavalier** [Widdershin/markdown-doctest#26]
Thanks for markdown-doctest 😄 

I tried to start converting most.js's unit tests to allow ES6 using babel 6 and babel-register.  The buster.js unit tests run, but markdown-doctest fails.  I figure this is related to #19.  [Here's a branch](https://github.com/cujojs/most/tree/allow-es6-tests) that's setup to use babel 6 to run the unit tests, and with no changes (vs. master) to the markdown-doctest version or config.  And [Here's the error output of running `npm test`](https://gist.github.com/briancavalier/a6adb50e4da644180b6713cea3d7a0e8).

Is this be possible now, or will it require #19?

Thanks!

**Comment by Widdershin** [comment]
Hi @briancavalier, I just need to land #19, which just needs to be updated and then tested. I'll make that a priority now 😄

**Comment by briancavalier** [comment]
Cool, thanks.

**Comment by Widdershin** [comment]
@briancavalier this should be fixed with the release of v0.5.0, please let me know how you get on 😄

**Comment by briancavalier** [comment]
Works!

<img width="425" alt="screen shot 2016-05-12 at 9 04 29 am" src="https://cloud.githubusercontent.com/assets/90518/15215459/b081b9da-1820-11e6-9fa7-be846957814a.png">

I only had to make [one small change](https://github.com/cujojs/most/commit/f6686417dd2be7c6151eb74d84ef1f3f279bcd21) to add `babel-polyfill` as a devDep and simplify the `require` in `.markdown-doctest-setup.js`.

Thanks again!
