### ISSUE TITLE
No red

### ISSUE THREAD

**Issue by staltz** [Widdershin/markdown-doctest#28]
Just a tiny feedback, when I get the report:
```

Passed: 10
Skipped: 6
Failed: 0
```

`Failed: 0` is in red. The color itself makes me alerted. I don't know, it's something about red. Perhaps it could be gray/white if `===0` and red if `>0` ?

**Comment by briancavalier** [comment]
I agree.  If everything goes perfectly, I think I'd like to see just green.  Some yellow for the skipped examples is ok--a good reminder.

**Comment by Widdershin** [comment]
Definitely agree, I'll fix this. Also considering removing the yellow skip S and just keeping the skipped count.

**Comment by Widdershin** [comment]
This is the new behaviour as of v0.6.0. I also removed the yellow skip S and just print the count skipped if there are any. Thanks for the suggestion 😄

**Comment by staltz** [comment]
Nice !

**Comment by briancavalier** [comment]
Just updated.  Well done!
