### ISSUE TITLE
The process doesn't exit when all tests pass.

### ISSUE THREAD

**Issue by jdalton** [Widdershin/markdown-doctest#30]
I noticed the process doesn't exit when all tests pass. It just sits.

**Comment by Widdershin** [comment]
Hi @jdalton!

This seems to be a bug specific to the `lodash` setup, and it looks like it hasn't always been happening.

I ran a bisect (manually) on lodash using `timeout npm run test:doc 20` and this is the first commit where it doesn't exit after a passing run:
```
commit a542f8ab542cc7ac1ead567ed74c38a7b24ea789
Author: John-David Dalton <john.david.dalton@gmail.com>
Date:   Thu May 19 13:52:18 2016 -0700

    Remove `clearTimeout` use.
```

I verified this was the problematic commit by checkout out to the prior one and it exits fine.

My guess is that one of the examples is running infinitely, or perhaps setting a timeout that was previously being cleared but is now not? I don't know enough about the `lodash` internals to know.

What do you think?

**Comment by Widdershin** [comment]
Here's a link to the commit in question: https://github.com/lodash/lodash/commit/a542f8ab54

**Comment by jdalton** [comment]
Neat side effect!
