### ISSUE TITLE
Allow customization of the line parser

### ISSUE THREAD

**Issue by bebraw** [Widdershin/markdown-doctest#47]
We have some custom code in the examples at [the maintenance book](https://github.com/survivejs/maintenance-book) we are writing (incidentally we'll cover your tool there as well so expect more people to find it). The problem is that there's no way to skip the custom code while processing.

I had a quick look and it seems we would have to extend the line parser so that you can pass a custom rule to it. We could skip lines containing `...` etc. there. This would allow us to check the book code using your tool.

We are disabling the broken examples for now but a parser level solution would be better.

**Comment by sapegin** [comment]
More customization examples:

* generate before and after versions of code that uses `leanpub-start-insert` and test them separately.

**Comment by Widdershin** [comment]
The maintenance book looks exciting, awesome that you're using markdown-doctest. I definitely want to help support your usecases.

I'm unsure about giving users the ability to extend the line parser, since it is really an implementation detail.

In this case, I wonder if instead we could add a function to the config that takes in the string form of each entire snippet, and returns a boolean indicating if it should be skipped.

So something like:

```js
module.exports = {
  skipExample: (example) => example.split('\n').some(line => line.match(/^\s*\.\.\.\s*$/))  
}
```

Do you think that would work for your usecase? I know we could make this function take in each line, but I think this might be more generally useful.

@sapegin I'm not sure I understand what `leanpub-start-insert` does, could you elaborate?

**Comment by bebraw** [comment]
@Widdershin The key thing here is that we want to know that the code executes (valid JavaScript). `skipExample` is an interesting idea that gets closer, though.

About `leanpub-start-insert`, consider the following example from the book:

```javascript
module.exports = {
  ...
  plugins: [
    ...
leanpub-start-insert
    'custom'
leanpub-end-insert
  ],
  rules: {
    ...
leanpub-start-insert
    'custom/demo': 1,
leanpub-end-insert
  }
};
```

To verify that the code runs before/after insertions, we would have to:

1. Eliminate `...`'s.
2. Generate two versions to check - one without the inserted code (the `leanpub-start-insert`, `leanpub-end-insert` blocks) and one with inserted code. Former is achieved by erasing the blocks entirely while the latter erases only the keywords.

To make things a bit more complex, there's also a block for removing code but it's the same idea in the end.

The ability to generate code to run would give us a nice degree of validation. If we break some block unintentionally (say, forget to add `leanpub-end-insert`), the code would crash (great thing).

So while `skipExample` would be a step to the right direction, it would miss a part of the point as it's better to validate the code than not

**Comment by sapegin** [comment]
Yep, looks like something like `processCode` would be more flexible. It could return an array of code snippets: 

* an empty array in case we want to skip the code block entirely;
* an array with before / after snippets in case of `leanpub-start-insert`.

And I’d eliminate `...`s just by commenting them ;-)

**Comment by Widdershin** [comment]
So perhaps what we want is a function that takes in all of the examples markdown doctest could find and returns any examples the user desires.

That handles filtering or making additional examples (map + flatten). My only concern with this API is that it might be too powerful, and might expose too much internal state. What do y'all think?

Sorry for the slow responses to this, I'm pretty swamped at the moment.

**Comment by bebraw** [comment]
What you propose would be enough to cover our use cases I think. 👍

**Comment by Widdershin** [comment]
I've been pretty swamped recently. Is anyone interested in making a pull
request to add this functionality?
